#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/glm5_next/modular_glm5_next.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_glm5_next.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""GLM5-Next KDA components ported from the official PyTorch implementation."""

from __future__ import annotations

import os
import sys
from dataclasses import dataclass

import torch
import torch.nn.functional as F
from torch import nn

sys.path.append(os.getcwd())

try:
    from ..utils.gated_delta import GatedDeltaCache, causal_conv1d_fn, causal_conv1d_update
    from ..utils.hyper_connection import ForgetGate, HyperConnection, HyperHead
    from ..utils.outputs import MoeCausalLMOutput
    from ..utils.training import load_balancing_loss
    from .configuration_glm5_next import Glm5NextConfig, Glm5NextTextConfig
    from .vision_modeling_glm5_next import Glm5NextVisionModel, Glm5NextVisionOutput
except ImportError:
    sys.path.append(os.path.dirname(os.path.dirname(__file__)))
    from configuration_glm5_next import Glm5NextConfig, Glm5NextTextConfig
    from vision_modeling_glm5_next import Glm5NextVisionModel, Glm5NextVisionOutput
    from utils.gated_delta import GatedDeltaCache, causal_conv1d_fn, causal_conv1d_update
    from utils.hyper_connection import ForgetGate, HyperConnection, HyperHead
    from utils.outputs import MoeCausalLMOutput
    from utils.training import load_balancing_loss


class Glm5NextTextRMSNormGated(nn.Module):
    """Official GLM5-Next strict-FP32 sigmoid RMSNormGated.

    Parameters:
        hidden_size: KDA head dimension.
        eps: Numerical stability constant.
    """

    def __init__(self, hidden_size: int, eps: float = 1e-6) -> None:
        """Create source normalization weight and sigmoid gating rule.

        Parameters:
            hidden_size: KDA head dimension.
            eps: Numerical stability constant.
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps
        self.activation = "sigmoid"

    def forward(self, hidden_states: torch.Tensor, gate: torch.Tensor) -> torch.Tensor:
        """Normalize in strict FP32 and apply the source sigmoid gate.

        Parameters:
            hidden_states: KDA output vectors.
            gate: Output-gate projection vectors.
        """
        input_dtype = hidden_states.dtype
        # Strict FP32 norm (do not downcast on the weights)
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim = True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        hidden_states = self.weight.to(torch.float32) * hidden_states
        # Apply gating
        return (hidden_states * torch.sigmoid(gate.to(torch.float32))).to(input_dtype)


def l2norm(hidden_states: torch.Tensor, dim: int = -1, eps: float = 1e-6) -> torch.Tensor:
    """Align with GLM5's FLA KDA L2 normalization convention.

    Parameters:
        hidden_states: Tensor to normalize.
        dim: Dimension over which squared norm is measured.
        eps: Numerical stability constant.
    """
    # main difference to qwen's gdn variation: intentionally use sqrt and / to match original triton
    return hidden_states / torch.sqrt((hidden_states * hidden_states).sum(dim = dim, keepdim = True) + eps)


def recurrent_kimi_delta_attention(
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    g: torch.Tensor,
    beta: torch.Tensor,
    initial_state: torch.Tensor | None = None,
    output_final_state: bool = False,
    use_qk_l2norm_in_kernel: bool = False,
) -> tuple[torch.Tensor, torch.Tensor | None]:
    """Run source recurrent Kimi Delta Attention in float32 state precision.

    Parameters:
        query: KDA queries shaped ``[batch, sequence, heads, head_dim]``.
        key: KDA keys shaped ``[batch, sequence, heads, head_dim]``.
        value: KDA values shaped ``[batch, sequence, heads, head_dim]``.
        g: Per-head log-space forget gates.
        beta: Per-head delta update rates.
        initial_state: Optional cached KDA recurrent state.
        output_final_state: Whether final state is returned.
        use_qk_l2norm_in_kernel: Whether source Q/K L2 normalization is enabled.
    """
    initial_dtype = query.dtype
    query, key, value, g, beta = [tensor.to(torch.float32) for tensor in (query, key, value, g, beta)]
    # important: FLA calculates these in fp32 so we do this after the float casts
    if use_qk_l2norm_in_kernel:
        query = l2norm(query, dim = -1, eps = 1e-6)
        key = l2norm(key, dim = -1, eps = 1e-6)
    batch_size, sequence_length, num_heads, key_head_dim = key.shape
    value_head_dim = value.shape[-1]
    query = query / (query.shape[-1] ** 0.5)
    core_attn_out = torch.zeros(batch_size, sequence_length, num_heads, value_head_dim, dtype = value.dtype, device = value.device)
    recurrent_state = (
        torch.zeros(batch_size, num_heads, key_head_dim, value_head_dim, dtype = value.dtype, device = value.device)
        if initial_state is None
        else initial_state.to(value)
    )
    # recurrent iteration
    for index in range(sequence_length):
        query_i, key_i, value_i = query[:, index], key[:, index], value[:, index]
        g_i = g[:, index][..., None].exp()
        beta_i = beta[:, index][..., None]
        recurrent_state = recurrent_state * g_i
        kv_memory = (recurrent_state * key_i[..., None]).sum(dim = -2)
        delta = (value_i - kv_memory) * beta_i
        recurrent_state = recurrent_state + key_i.unsqueeze(-1) * delta.unsqueeze(-2)
        core_attn_out[:, index] = (recurrent_state * query_i.unsqueeze(-1)).sum(dim = -2)
    return core_attn_out.to(initial_dtype), recurrent_state if output_final_state else None


class Glm5NextTextLinearAttention(nn.Module):
    """Kimi-style KDA (Kimi Linear Attention) for GLM-5.3-Flash.

    Parameters:
        config: GLM5-Next text configuration.
        layer_idx: Decoder-layer index used for recurrent cache state.
    """

    def __init__(self, config: Glm5NextTextConfig, layer_idx: int) -> None:
        """Create source Q/K/V, short-conv, forget, output-gate, and output projections.

        Parameters:
            config: GLM5-Next text configuration.
            layer_idx: Decoder-layer index.
        """
        super().__init__()
        self.hidden_size = config.hidden_size
        self.num_heads = config.linear_num_heads
        self.head_dim = config.linear_head_dim
        self.qkv_dim = self.head_dim * self.num_heads
        self.conv_kernel_size = config.linear_conv_kernel_dim
        self.layer_idx = layer_idx
        self.activation = config.hidden_act
        self.q_proj = nn.Linear(self.hidden_size, self.qkv_dim, bias = False)
        self.k_proj = nn.Linear(self.hidden_size, self.qkv_dim, bias = False)
        self.v_proj = nn.Linear(self.hidden_size, self.qkv_dim, bias = False)
        self.conv_dim = self.qkv_dim * 3
        self.conv1d = nn.Conv1d(self.conv_dim, self.conv_dim, bias = False, kernel_size = self.conv_kernel_size, groups = self.conv_dim, padding = self.conv_kernel_size - 1)
        self.forget_gate = ForgetGate(config)
        self.b_proj = nn.Linear(self.hidden_size, self.num_heads, bias = False)
        self.g_a_proj = nn.Linear(self.hidden_size, self.head_dim, bias = False)
        self.g_b_proj = nn.Linear(self.head_dim, self.qkv_dim, bias = False)
        self.o_norm = Glm5NextTextRMSNormGated(self.head_dim, eps = config.rms_norm_eps)
        self.o_proj = nn.Linear(self.qkv_dim, self.hidden_size, bias = False)
        self.layer_type = config.layer_types[layer_idx]

    def forward(
        self,
        hidden_states: torch.Tensor,
        cache_params: GatedDeltaCache | None = None,
        attention_mask: torch.Tensor | None = None,
    ) -> torch.Tensor:
        """Run source KDA projections, causal short convolution, and recurrence.

        Parameters:
            hidden_states: Input token states.
            cache_params: Optional per-layer short-conv and recurrent KDA cache.
            attention_mask: Optional boolean padding mask.
        """
        if attention_mask is not None:
            hidden_states = (hidden_states * attention_mask[:, :, None]).to(hidden_states.dtype)
        batch_size, sequence_length = hidden_states.shape[:2]
        hidden_shape = (batch_size, sequence_length, -1, self.head_dim)
        mixed_qkv = torch.cat([self.q_proj(hidden_states), self.k_proj(hidden_states), self.v_proj(hidden_states)], dim = -1).transpose(1, 2)
        conv_state = None if cache_params is None else cache_params.conv_states.get(self.layer_idx)
        if conv_state is not None:
            mixed_qkv = causal_conv1d_update(mixed_qkv, conv_state, self.conv1d.weight.squeeze(1), self.conv1d.bias, self.activation)
        else:
            projected_qkv = mixed_qkv
            mixed_qkv = causal_conv1d_fn(projected_qkv, self.conv1d.weight.squeeze(1), self.conv1d.bias, self.activation)
            if cache_params is not None:
                cache_params.conv_states[self.layer_idx] = projected_qkv[:, :, -self.conv_kernel_size + 1 :].detach()
        query, key, value = torch.split(mixed_qkv.transpose(1, 2), [self.qkv_dim] * 3, dim = -1)
        query, key, value = query.view(hidden_shape), key.view(hidden_shape), value.view(hidden_shape)
        g = self.forget_gate(hidden_states)
        beta = torch.sigmoid(self.b_proj(hidden_states))
        initial_state = None if cache_params is None else cache_params.recurrent_states.get(self.layer_idx)
        core_attn_out, final_state = recurrent_kimi_delta_attention(
            query,
            key,
            value,
            g = g,
            beta = beta,
            initial_state = initial_state,
            output_final_state = cache_params is not None,
            use_qk_l2norm_in_kernel = True,
        )
        if cache_params is not None and final_state is not None:
            cache_params.recurrent_states[self.layer_idx] = final_state.detach()
        gate = self.g_b_proj(self.g_a_proj(hidden_states)).view(hidden_shape)
        output = self.o_norm(core_attn_out, gate).reshape(batch_size, sequence_length, -1)
        return self.o_proj(output)


class Glm5NextTextRMSNorm(nn.Module):
    """GLM5-Next RMSNorm is equivalent to T5LayerNorm.

    Parameters:
        hidden_size: Feature dimension.
        eps: Numerical stability constant.
    """

    def __init__(self, hidden_size: int, eps: float = 1e-6) -> None:
        """Create the official learned RMS scale.

        Parameters:
            hidden_size: Feature dimension.
            eps: Numerical stability constant.
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        """Normalize the final feature axis in FP32.

        Parameters:
            hidden_states: Input activations.
        """
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim = True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)


class Glm5NextCache(GatedDeltaCache):
    """Minimal local cache combining GLM5 KDA, MLA-KV, and DSA-indexer states.

    Parameters:
        None.
    """

    def __init__(self) -> None:
        """Initialize per-layer cache dictionaries.

        Parameters:
            None.
        """
        super().__init__()
        self.key_cache: dict[int, torch.Tensor] = {}
        self.value_cache: dict[int, torch.Tensor] = {}
        self.indexer_states: dict[int, torch.Tensor] = {}

    def get_seq_length(self, layer_idx: int | None = None) -> int:
        """Return cached KV length, falling back to indexer or KDA state.

        Parameters:
            layer_idx: Optional decoder-layer index.
        """
        indices = [layer_idx] if layer_idx is not None else list(self.key_cache)
        for index in indices:
            if index in self.key_cache:
                return self.key_cache[index].shape[-2]
        indices = [layer_idx] if layer_idx is not None else list(self.indexer_states)
        for index in indices:
            if index in self.indexer_states:
                return self.indexer_states[index].shape[1]
        return 0

    def update(
        self,
        key_states: torch.Tensor,
        value_states: torch.Tensor,
        layer_idx: int,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Append MLA key/value tensors and return the complete cache.

        Parameters:
            key_states: New keys shaped ``[B, heads, S, D]``.
            value_states: New values shaped ``[B, heads, S, D]``.
            layer_idx: Owning decoder layer.
        """
        if layer_idx in self.key_cache:
            key_states = torch.cat([self.key_cache[layer_idx], key_states], dim = -2)
            value_states = torch.cat([self.value_cache[layer_idx], value_states], dim = -2)
        self.key_cache[layer_idx] = key_states.detach()
        self.value_cache[layer_idx] = value_states.detach()
        return key_states, value_states

    def update_indexer(self, states: torch.Tensor, layer_idx: int) -> torch.Tensor:
        """Append packed DSA indexer inputs for a decoder layer.

        Parameters:
            states: Packed key, gate-score, and validity states.
            layer_idx: Owning decoder layer.
        """
        if layer_idx in self.indexer_states:
            states = torch.cat([self.indexer_states[layer_idx], states], dim = 1)
        self.indexer_states[layer_idx] = states.detach()
        return states


class Glm5NextTextMLP(nn.Module):
    """Official dense GLM5-Next SwiGLU MLP with output clamps.

    Parameters:
        config: GLM5-Next text configuration.
        intermediate_size: Optional override used by shared experts.
    """

    def __init__(self, config: Glm5NextTextConfig, intermediate_size: int | None = None) -> None:
        """Create source MLP projections.

        Parameters:
            config: GLM5-Next text configuration.
            intermediate_size: Optional intermediate dimension.
        """
        super().__init__()
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size if intermediate_size is None else intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias = False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias = False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias = False)
        self.swiglu_limit = config.swiglu_limit

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        """Apply source clamped SwiGLU.

        Parameters:
            hidden_states: Input token states.
        """
        gate = self.gate_proj(hidden_states).clamp(min = None, max = self.swiglu_limit)
        up = self.up_proj(hidden_states).clamp(min = -self.swiglu_limit, max = self.swiglu_limit)
        return self.down_proj(F.silu(gate) * up)


class Glm5NextTextExperts(nn.Module):
    """Collection of expert weights stored as 3D tensors."""

    def __init__(self, config: Glm5NextTextConfig) -> None:
        """Create packed routed-expert projections.

        Parameters:
            config: GLM5-Next text configuration.
        """
        super().__init__()
        self.num_experts = config.num_local_experts
        self.hidden_dim = config.hidden_size
        self.intermediate_dim = config.moe_intermediate_size
        self.gate_up_proj = nn.Parameter(torch.empty(self.num_experts, 2 * self.intermediate_dim, self.hidden_dim))
        self.down_proj = nn.Parameter(torch.empty(self.num_experts, self.hidden_dim, self.intermediate_dim))
        self.swiglu_limit = config.swiglu_limit

    def forward(
        self,
        hidden_states: torch.Tensor,
        top_k_index: torch.Tensor,
        top_k_weights: torch.Tensor,
    ) -> torch.Tensor:
        """Run only experts selected by the source grouped router.

        Parameters:
            hidden_states: Flattened token states.
            top_k_index: Selected expert indices per token.
            top_k_weights: Selected source sigmoid routing weights.
        """
        final = torch.zeros_like(hidden_states)
        for expert_idx in torch.unique(top_k_index):
            expert = int(expert_idx)
            token_indices, topk_positions = torch.where(top_k_index == expert)
            gate_up = F.linear(hidden_states[token_indices], self.gate_up_proj[expert])
            gate, up = gate_up.chunk(2, dim = -1)
            gate = gate.clamp(min = None, max = self.swiglu_limit)
            up = up.clamp(min = -self.swiglu_limit, max = self.swiglu_limit)
            current = F.linear(F.silu(gate) * up, self.down_proj[expert])
            final.index_add_(0, token_indices, current * top_k_weights[token_indices, topk_positions, None])
        return final


class Glm5NextTextTopkRouter(nn.Module):
    """Official grouped sigmoid Top-k router including correction bias."""

    def __init__(self, config: Glm5NextTextConfig) -> None:
        """Create source router weights and selection controls.

        Parameters:
            config: GLM5-Next text configuration.
        """
        super().__init__()
        self.top_k = config.num_experts_per_tok
        self.num_experts = config.num_local_experts
        self.hidden_dim = config.hidden_size
        self.weight = nn.Parameter(torch.zeros(self.num_experts, self.hidden_dim))
        self.routed_scaling_factor = config.routed_scaling_factor
        self.num_group = config.n_group
        self.topk_group = config.topk_group
        self.norm_topk_prob = config.norm_topk_prob
        self.register_buffer("e_score_correction_bias", torch.zeros(self.num_experts))

    def forward(self, hidden_states: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Return source logits, selected weights, and selected expert ids.

        Parameters:
            hidden_states: Input states with arbitrary leading dimensions.
        """
        tokens = hidden_states.reshape(-1, self.hidden_dim)
        router_logits = F.linear(tokens.float(), self.weight.float())
        scores = router_logits.sigmoid()
        scores_for_choice = scores + self.e_score_correction_bias
        groups = scores_for_choice.view(-1, self.num_group, self.num_experts // self.num_group)
        group_scores = groups.topk(2, dim = -1).values.sum(dim = -1)
        group_idx = group_scores.topk(self.topk_group, dim = -1, sorted = False).indices
        group_mask = torch.zeros_like(group_scores).scatter_(1, group_idx, 1)
        score_mask = group_mask.unsqueeze(-1).expand_as(groups).reshape(-1, self.num_experts)
        selected_scores = scores_for_choice.masked_fill(~score_mask.bool(), float("-inf"))
        topk_indices = selected_scores.topk(self.top_k, dim = -1, sorted = False).indices
        topk_weights = scores.gather(1, topk_indices)
        if self.norm_topk_prob:
            topk_weights = topk_weights / (topk_weights.sum(dim = -1, keepdim = True) + 1e-20)
        return router_logits, topk_weights * self.routed_scaling_factor, topk_indices


class Glm5NextTextMoE(nn.Module):
    """A mixed expert module containing shared experts."""

    def __init__(self, config: Glm5NextTextConfig) -> None:
        """Create routed and shared experts.

        Parameters:
            config: GLM5-Next text configuration.
        """
        super().__init__()
        self.experts = Glm5NextTextExperts(config)
        self.gate = Glm5NextTextTopkRouter(config)
        self.shared_experts = Glm5NextTextMLP(config, config.moe_intermediate_size * config.n_shared_experts)

    def forward(self, hidden_states: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Add routed-expert output and source shared-expert residual.

        Parameters:
            hidden_states: Input token states.
        """
        residuals = hidden_states
        original_shape = hidden_states.shape
        router_logits, topk_weights, topk_indices = self.gate(hidden_states)
        routed = self.experts(hidden_states.reshape(-1, hidden_states.shape[-1]), topk_indices, topk_weights)
        routed = routed.reshape(original_shape)
        return routed + self.shared_experts(residuals), router_logits


class Glm5NextTextIndexer(nn.Module):
    """DeepSeek Sparse Attention (DSA) indexer with k-pool compression for GLM-5.3-Flash.

    The indexer uses lightweight projections (``wq_b``, ``wk``) separate from the main MLA
    attention path. It scores compressed k-pool candidates, expands selected pools back
    into raw cache indices, and optionally appends the current incomplete tail pool.
    """

    def __init__(self, config: Glm5NextTextConfig, layer_idx: int) -> None:
        """Create source index projections and k-pool parameters.

        Parameters:
            config: GLM5-Next text configuration.
            layer_idx: Owning decoder layer.
        """
        super().__init__()
        self.layer_idx = layer_idx
        self.n_heads = config.index_n_heads
        self.head_dim = config.index_head_dim
        self.index_topk = config.index_topk
        self.q_lora_rank = config.q_lora_rank
        self.wq_b = nn.Linear(self.q_lora_rank, self.n_heads * self.head_dim, bias = False)
        self.wk = nn.Linear(config.hidden_size, self.head_dim, bias = False)
        self.k_norm = nn.LayerNorm(self.head_dim, eps = 1e-6)
        self.weights_proj = nn.Linear(config.hidden_size, self.n_heads, bias = False)
        self.softmax_scale = self.head_dim ** -0.5
        self.index_kpool = config.index_kpool
        self.index_kpool_always_select_tail = config.index_kpool_always_select_tail
        self.index_kpool_compress_ape = nn.Parameter(torch.zeros(self.index_kpool, self.head_dim))
        self.index_kpool_compress_gate = nn.Parameter(torch.zeros(self.head_dim, config.hidden_size))

    def forward(
        self,
        hidden_states: torch.Tensor,
        q_resid: torch.Tensor,
        attention_mask: torch.Tensor,
        past_key_values: Glm5NextCache | None,
    ) -> torch.Tensor:
        """Select top-k visible token indices for each DSA query.

        Parameters:
            hidden_states: Input states ``[B, S, hidden_size]``.
            q_resid: Normalized Q-LoRA residual.
            attention_mask: Boolean padding mask for current tokens.
            past_key_values: Optional local cache containing indexer state.
        """
        batch_size, seq_len = hidden_states.shape[:2]
        q = self.wq_b(q_resid).view(batch_size, seq_len, self.n_heads, self.head_dim)
        key = self.k_norm(self.wk(hidden_states)).view(batch_size, seq_len, self.head_dim)
        gate_scores = F.linear(hidden_states, self.index_kpool_compress_gate)
        packed_states = torch.cat([key, gate_scores, attention_mask.to(key.dtype)[..., None]], dim = -1)
        current_length = seq_len
        if past_key_values is not None:
            packed_states = past_key_values.update_indexer(packed_states, self.layer_idx)
            current_length = packed_states.shape[1]
        valid_keys = packed_states[..., -1].bool()
        visible_tokens = self.get_visible_tokens(valid_keys, seq_len, current_length)
        pool_keys, pool_indices, pool_valid = self.get_pooled_states(packed_states)
        scores = torch.matmul(q.float(), pool_keys.transpose(-1, -2).float().unsqueeze(1))
        scores = F.relu(scores * self.softmax_scale)
        weights = self.weights_proj(hidden_states.to(self.weights_proj.weight.dtype)).float() * (self.n_heads ** -0.5)
        index_scores = torch.matmul(weights.unsqueeze(-2), scores).squeeze(-2)
        pool_end = pool_indices[..., -1].clamp(0, packed_states.shape[1] - 1)
        pool_visible = visible_tokens.gather(-1, pool_end[:, None, :].expand(batch_size, seq_len, -1))
        valid_candidates = pool_visible & pool_valid[:, None]
        index_scores = index_scores.masked_fill(~valid_candidates, torch.finfo(index_scores.dtype).min)
        select_k = min(self.index_topk // self.index_kpool, index_scores.shape[-1])
        selected = index_scores.topk(select_k, dim = -1).indices
        selected_valid = valid_candidates.gather(-1, selected)
        batch_idx = torch.arange(batch_size, device = hidden_states.device)[:, None, None]
        selected_indices = pool_indices[batch_idx, selected]
        topk_indices = selected_indices.flatten(-2).masked_fill(
            ~selected_valid[..., None].expand_as(selected_indices).flatten(-2), -1
        )
        output_width = self.index_topk
        if self.index_kpool_always_select_tail:
            topk_indices = self.append_visible_tail(topk_indices, visible_tokens, valid_keys)
            output_width += self.index_kpool - 1
        topk_indices = F.pad(topk_indices, (0, output_width - topk_indices.shape[-1]), value = -1)[..., :output_width]
        return topk_indices.masked_fill(~attention_mask[..., None], -1).to(torch.int32)

    def get_visible_tokens(
        self,
        valid_keys: torch.Tensor,
        q_length: int,
        current_length: int,
    ) -> torch.Tensor:
        """Check query visibility based on causality and cached padding state.

        Parameters:
            valid_keys: Cached key validity flags.
            q_length: Current query length.
            current_length: Current cache length.
        """
        kv_positions = torch.arange(valid_keys.shape[-1], device = valid_keys.device)
        q_positions = current_length - q_length + torch.arange(q_length, device = valid_keys.device)
        causal = kv_positions[None, None, :] <= q_positions[None, :, None]
        return causal & valid_keys[:, None, :]

    def get_pooled_states(self, packed_states: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Build compressed k-pool candidates from packed indexer state.

        Pooling starts at the first real token, not raw slot zero. This is the part
        that makes ``[P, P, A, B, C, D]`` behave like ``[A, B, C, D]``.

        Parameters:
            packed_states: Cached indexer states.
        """
        keys, gate_scores, valid_keys = torch.split(packed_states, [self.head_dim, self.head_dim, 1], dim = -1)
        valid_keys = valid_keys.bool().squeeze(-1)
        batch_size, seq_len = keys.shape[:2]
        pools = (seq_len + self.index_kpool - 1) // self.index_kpool
        first_key = torch.where(
            valid_keys.any(-1),
            valid_keys.long().argmax(-1),
            torch.full((batch_size,), seq_len, dtype = torch.long, device = keys.device),
        )
        offsets = torch.arange(pools * self.index_kpool, device = keys.device).view(1, pools, self.index_kpool)
        pool_indices = first_key[:, None, None] + offsets
        batch_idx = torch.arange(batch_size, device = keys.device)[:, None, None]
        safe_indices = pool_indices.clamp(0, seq_len - 1)
        grouped_keys = keys[batch_idx, safe_indices]
        grouped_gate_scores = gate_scores[batch_idx, safe_indices]
        grouped_valid_keys = valid_keys[batch_idx, safe_indices] & (pool_indices < seq_len)
        pool_valid = grouped_valid_keys.all(-1)
        pool_indices = pool_indices.masked_fill(~grouped_valid_keys, -1)
        # Learn a weighted average over tokens inside each complete pool.
        logits = grouped_gate_scores.float() + self.index_kpool_compress_ape.float()[None, None]
        logits = logits.masked_fill(~grouped_valid_keys[..., None], float("-inf"))
        probabilities = torch.nan_to_num(logits.softmax(dim = 2)).to(grouped_keys.dtype)
        pool_keys = (probabilities * grouped_keys).sum(dim = 2)
        keep = pool_valid.any(0)
        return pool_keys[:, keep], pool_indices[:, keep], pool_valid[:, keep]

    def append_visible_tail(
        self,
        topk_indices: torch.Tensor,
        token_visible: torch.Tensor,
        key_valid: torch.Tensor,
    ) -> torch.Tensor:
        """Append the current incomplete k-pool as raw visible token indices.

        Parameters:
            topk_indices: Selected pooled token ids.
            token_visible: Per-query visibility mask.
            key_valid: Cached padding validity flags.
        """
        max_tail_width = self.index_kpool - 1
        if max_tail_width == 0:
            return topk_indices
        batch_size, _, kv_length = token_visible.shape
        first_key = torch.where(
            key_valid.any(-1),
            key_valid.long().argmax(-1),
            torch.full((batch_size,), kv_length, dtype = torch.long, device = token_visible.device),
        )
        visible_count = token_visible.long().sum(-1)
        tail_count = visible_count.remainder(self.index_kpool)
        tail_offsets = torch.arange(max_tail_width, device = token_visible.device)
        tail_indices = first_key[:, None, None] + visible_count[..., None] - tail_count[..., None] + tail_offsets
        tail_valid = (tail_offsets[None, None] < tail_count[..., None]) & tail_indices.lt(kv_length)
        tail_visible = token_visible.gather(-1, tail_indices.clamp(0, kv_length - 1))
        return torch.cat([topk_indices, tail_indices.masked_fill(~(tail_valid & tail_visible), -1)], dim = -1)


class Glm5NextTextAttention(nn.Module):
    """DeepSeek-V3 MLA plus the GLM5 DSA indexer and cross-layer top-k sharing."""

    def __init__(self, config: Glm5NextTextConfig, layer_idx: int) -> None:
        """Create official Q-LoRA, KV-LoRA, MLA, and DSA projections.

        Parameters:
            config: GLM5-Next text configuration.
            layer_idx: Owning decoder layer.
        """
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.attention_dropout = config.attention_dropout
        self.hidden_size = config.hidden_size
        self.num_heads = config.num_attention_heads
        self.q_lora_rank = config.q_lora_rank
        self.kv_lora_rank = config.kv_lora_rank
        self.v_head_dim = config.v_head_dim
        self.qk_nope_head_dim = config.qk_nope_head_dim
        self.qk_rope_head_dim = config.qk_rope_head_dim
        self.qk_head_dim = self.qk_nope_head_dim + self.qk_rope_head_dim
        self.q_a_proj = nn.Linear(self.hidden_size, self.q_lora_rank, bias = config.attention_bias)
        self.q_a_layernorm = Glm5NextTextRMSNorm(self.q_lora_rank, eps = config.rms_norm_eps)
        self.q_b_proj = nn.Linear(self.q_lora_rank, self.num_heads * self.qk_head_dim, bias = False)
        self.kv_a_proj_with_mqa = nn.Linear(
            self.hidden_size,
            self.kv_lora_rank + self.qk_rope_head_dim,
            bias = config.attention_bias,
        )
        self.kv_a_layernorm = Glm5NextTextRMSNorm(self.kv_lora_rank, eps = config.rms_norm_eps)
        self.kv_b_proj = nn.Linear(
            self.kv_lora_rank,
            self.num_heads * (self.qk_nope_head_dim + self.v_head_dim),
            bias = False,
        )
        self.o_proj = nn.Linear(self.num_heads * self.v_head_dim, self.hidden_size, bias = config.attention_bias)
        self.scaling = self.qk_head_dim ** -0.5
        # Refer: https://arxiv.org/abs/2603.12201 for more details.
        self.skip_topk = config.indexer_types[layer_idx] == "shared"
        self.indexer = None if self.skip_topk else Glm5NextTextIndexer(config, layer_idx)
        next_layer = min(layer_idx + 1, len(config.indexer_types) - 1)
        self.next_skip_topk = not self.skip_topk and config.indexer_types[next_layer] == "shared"

    def expand_kv(self, kv_nope: torch.Tensor, k_rot: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Expand compressed MLA latents into full key and value states.

        Parameters:
            kv_nope: Normalized KV low-rank states.
            k_rot: Shared positional-key part; empty for the current GLM5 config.
        """
        batch_size, _, seq_len, _ = kv_nope.shape
        projected = self.kv_b_proj(kv_nope).view(batch_size, seq_len, self.num_heads, -1).transpose(1, 2)
        k_nope, value_states = torch.split(projected, [self.qk_nope_head_dim, self.v_head_dim], dim = -1)
        if self.qk_rope_head_dim == 0:
            return k_nope, value_states
        k_rot = k_rot.expand(-1, k_nope.shape[1], -1, -1)
        return torch.cat([k_nope, k_rot], dim = -1), value_states

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
        past_key_values: Glm5NextCache | None = None,
        prev_topk_indices: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor | None, torch.Tensor | None]:
        """Run MLA projections, DSA selection, and eager sparse attention.

        Parameters:
            hidden_states: Input token states.
            attention_mask: Current boolean padding mask.
            past_key_values: Optional local cache.
            prev_topk_indices: DSA mask shared by the preceding full indexer layer.
        """
        batch_size, seq_len = hidden_states.shape[:2]
        q_resid = self.q_a_layernorm(self.q_a_proj(hidden_states))
        query_states = self.q_b_proj(q_resid).view(batch_size, seq_len, self.num_heads, self.qk_head_dim).transpose(1, 2)
        compressed_kv = self.kv_a_proj_with_mqa(hidden_states)
        kv_pass, k_rot = torch.split(compressed_kv, [self.kv_lora_rank, self.qk_rope_head_dim], dim = -1)
        k_pass = self.kv_a_layernorm(kv_pass).view(batch_size, 1, seq_len, self.kv_lora_rank)
        k_rot = k_rot.view(batch_size, 1, seq_len, self.qk_rope_head_dim)
        key_states, value_states = self.expand_kv(k_pass, k_rot)
        if past_key_values is not None:
            key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx)
        if self.indexer is None:
            if prev_topk_indices is None:
                raise ValueError("Shared DSA layers require top-k indices from a previous full indexer layer.")
            topk_indices = prev_topk_indices
        else:
            topk_indices = self.indexer(hidden_states, q_resid, attention_mask, past_key_values)
        sparse_mask = self.build_attention_mask_from_topk(topk_indices, query_states, key_states.shape[2])
        scores = torch.matmul(query_states, key_states.transpose(-1, -2)) * self.scaling
        scores = scores.masked_fill(~sparse_mask, torch.finfo(scores.dtype).min)
        probabilities = F.softmax(scores, dim = -1, dtype = torch.float32).to(query_states.dtype)
        probabilities = F.dropout(probabilities, p = self.attention_dropout, training = self.training)
        output = torch.matmul(probabilities, value_states).transpose(1, 2).reshape(batch_size, seq_len, -1)
        output = self.o_proj(output)
        return output, probabilities, topk_indices if self.next_skip_topk else None

    @staticmethod
    def build_attention_mask_from_topk(
        topk_indices: torch.Tensor,
        query_states: torch.Tensor,
        kv_length: int,
    ) -> torch.Tensor:
        """Convert raw selected ids into the sparse mask used by eager attention.

        Only eager/SDPA are supported upstream: sparse query-to-key selections cannot
        be represented by Flash Attention without a custom index-selection kernel.

        Parameters:
            topk_indices: Source ``-1``-padded sparse index ids.
            query_states: Query tensor used only for device/dtype compatibility.
            kv_length: Number of cached key positions.
        """
        topk_valid = topk_indices.ge(0) & topk_indices.lt(kv_length)
        safe_indices = topk_indices.clamp(0, kv_length - 1)
        counts = torch.zeros(
            topk_indices.shape[0],
            topk_indices.shape[1],
            kv_length,
            dtype = torch.int32,
            device = query_states.device,
        )
        counts.scatter_add_(-1, safe_indices, topk_valid.to(torch.int32))
        return counts.ne(0).unsqueeze(1)


class Glm5NextTextDecoderLayer(nn.Module):
    """Official GLM5 decoder layer with mHC attention and MLP residual sites."""

    def __init__(self, config: Glm5NextTextConfig, layer_idx: int) -> None:
        """Create source attention type, MLP type, norms, and hyper-connections.

        Parameters:
            config: GLM5-Next text configuration.
            layer_idx: Decoder-layer index.
        """
        super().__init__()
        self.block_type = config.layer_types[layer_idx]
        self.self_attn = (
            Glm5NextTextLinearAttention(config, layer_idx)
            if self.block_type == "linear_attention"
            else Glm5NextTextAttention(config, layer_idx)
        )
        self.mlp = Glm5NextTextMoE(config) if config.mlp_layer_types[layer_idx] == "sparse" else Glm5NextTextMLP(config)
        self.input_layernorm = Glm5NextTextRMSNorm(config.hidden_size, config.rms_norm_eps)
        self.post_attention_layernorm = Glm5NextTextRMSNorm(config.hidden_size, config.rms_norm_eps)
        self.attn_hc = HyperConnection(config)
        self.ffn_hc = HyperConnection(config)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: torch.Tensor,
        past_key_values: Glm5NextCache | None = None,
        prev_topk_indices: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor | None, torch.Tensor | None]:
        """Apply attention then feed-forward through the source mHC residual rules.

        Parameters:
            hidden_states: Parallel mHC residual streams ``[B, S, H, D]``.
            attention_mask: Boolean padding mask.
            past_key_values: Optional GLM5 local cache.
            prev_topk_indices: Shared DSA indices from prior layer.
        """
        dtype = hidden_states.dtype
        residual = hidden_states
        post, comb, collapsed = self.attn_hc(hidden_states)
        collapsed = self.input_layernorm(collapsed)
        if self.block_type == "linear_attention":
            attention_output = self.self_attn(collapsed, cache_params = past_key_values, attention_mask = attention_mask)
            topk_indices = None
        else:
            attention_output, _, topk_indices = self.self_attn(
                collapsed,
                attention_mask,
                past_key_values,
                prev_topk_indices,
            )
        hidden_states = post.to(dtype).unsqueeze(-1) * attention_output.unsqueeze(-2) + torch.matmul(
            comb.to(dtype).transpose(-1, -2), residual
        )
        residual = hidden_states
        post, comb, collapsed = self.ffn_hc(hidden_states)
        collapsed = self.post_attention_layernorm(collapsed)
        if isinstance(self.mlp, Glm5NextTextMoE):
            feed_forward, router_logits = self.mlp(collapsed)
        else:
            feed_forward, router_logits = self.mlp(collapsed), None
        hidden_states = post.to(dtype).unsqueeze(-1) * feed_forward.unsqueeze(-2) + torch.matmul(
            comb.to(dtype).transpose(-1, -2), residual
        )
        return hidden_states, topk_indices, router_logits


def initialize_glm5_next_weights(module: nn.Module, initializer_range: float) -> None:
    """Apply the relevant official GLM5-Next initialization rules.

    Parameters:
        module: Module visited by ``nn.Module.apply``.
        initializer_range: Standard deviation used by source linear projections.
    """
    if isinstance(module, (nn.Linear, nn.Embedding, nn.Conv1d)):
        nn.init.normal_(module.weight, mean = 0.0, std = initializer_range)
        if getattr(module, "bias", None) is not None:
            nn.init.zeros_(module.bias)
    elif isinstance(module, Glm5NextTextExperts):
        nn.init.normal_(module.gate_up_proj, mean = 0.0, std = initializer_range)
        nn.init.normal_(module.down_proj, mean = 0.0, std = initializer_range)
    elif isinstance(module, Glm5NextTextTopkRouter):
        nn.init.zeros_(module.e_score_correction_bias)
        nn.init.normal_(module.weight, mean = 0.0, std = initializer_range)
    elif isinstance(module, Glm5NextTextIndexer):
        nn.init.zeros_(module.index_kpool_compress_ape)
        nn.init.ones_(module.index_kpool_compress_gate)
    elif isinstance(module, HyperConnection):
        nn.init.normal_(module.fn, mean = 0.0, std = 0.02)
        nn.init.zeros_(module.base)
        nn.init.ones_(module.scale)
    elif isinstance(module, ForgetGate):
        # Following FLA initialization. This is incredibly important so keep it this way.
        if module.safe_gate_lower_bound is not None:
            nn.init.zeros_(module.A_log)
        else:
            nn.init.uniform_(module.A_log, a = 1.0, b = 16.0)
            module.A_log.data.log_()
        nn.init.uniform_(module.dt_bias, a = -6.907755, b = -2.302585)
    elif isinstance(module, (Glm5NextTextRMSNorm, Glm5NextTextRMSNormGated)):
        nn.init.ones_(module.weight)


@dataclass
class Glm5NextTextModelOutput:
    """Framework-free output used by ``Glm5NextTextModel``.

    Parameters:
        last_hidden_state: Final normalized text states.
        past_key_values: Optional local mixed attention cache.
        router_logits: Optional sparse-MoE routing logits.
    """

    last_hidden_state: torch.Tensor
    past_key_values: Glm5NextCache | None = None
    router_logits: tuple[torch.Tensor, ...] | None = None


class Glm5NextTextModel(nn.Module):
    """GLM5-Next text backbone without Transformers runtime integration."""

    def __init__(self, config: Glm5NextTextConfig) -> None:
        """Create embeddings, official hybrid decoder stack, and mHC output head.

        Parameters:
            config: GLM5-Next text configuration.
        """
        super().__init__()
        config.validate_architecture()
        self.config = config
        padding_idx = config.pad_token_id if config.pad_token_id is not None and config.pad_token_id < config.vocab_size else None
        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, padding_idx)
        self.layers = nn.ModuleList([Glm5NextTextDecoderLayer(config, index) for index in range(config.num_hidden_layers)])
        self.norm = Glm5NextTextRMSNorm(config.hidden_size, eps = config.rms_norm_eps)
        self.hc_head = HyperHead()
        self.apply(lambda module: initialize_glm5_next_weights(module, config.initializer_range))

    def forward(
        self,
        input_ids: torch.Tensor | None = None,
        attention_mask: torch.Tensor | None = None,
        past_key_values: Glm5NextCache | None = None,
        inputs_embeds: torch.Tensor | None = None,
        use_cache: bool | None = None,
        output_router_logits: bool = False,
    ) -> Glm5NextTextModelOutput:
        """Run the official hybrid KDA/DSA decoder schedule.

        Parameters:
            input_ids: Token ids, mutually exclusive with ``inputs_embeds``.
            attention_mask: Optional current-token padding mask.
            past_key_values: Optional local KDA/MLA/DSA cache.
            inputs_embeds: Precomputed embeddings, mutually exclusive with ``input_ids``.
            use_cache: Create and return cache when true.
            output_router_logits: Return sparse-MoE router diagnostics.
        """
        if (input_ids is None) == (inputs_embeds is None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")
        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)
        if attention_mask is None:
            attention_mask = torch.ones(inputs_embeds.shape[:2], dtype = torch.bool, device = inputs_embeds.device)
        else:
            attention_mask = attention_mask.bool()
        if use_cache and past_key_values is None:
            past_key_values = Glm5NextCache()
        # Source mHC starts by copying every token into hc_mult residual streams.
        hidden_states = inputs_embeds.unsqueeze(2).expand(-1, -1, self.config.hc_mult, -1).contiguous()
        shared_topk = None
        router_logits: list[torch.Tensor] = []
        for layer in self.layers:
            hidden_states, shared_topk, layer_router_logits = layer(
                hidden_states,
                attention_mask,
                past_key_values,
                shared_topk,
            )
            if output_router_logits and layer_router_logits is not None:
                router_logits.append(layer_router_logits)
        hidden_states = self.norm(self.hc_head(hidden_states))
        return Glm5NextTextModelOutput(
            last_hidden_state = hidden_states,
            past_key_values = past_key_values,
            router_logits = tuple(router_logits) if output_router_logits else None,
        )


class Glm5NextForCausalLM(nn.Module):
    """Standalone GLM5-Next text causal language model.

    Parameters:
        config: GLM5-Next text configuration.
    """

    def __init__(self, config: Glm5NextTextConfig) -> None:
        """Create the source text model and untied LM head.

        Parameters:
            config: GLM5-Next text configuration.
        """
        super().__init__()
        self.config = config
        self.model = Glm5NextTextModel(config)
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias = False)
        initialize_glm5_next_weights(self.lm_head, config.initializer_range)

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        past_key_values: Glm5NextCache | None = None,
        use_cache: bool = False,
        labels: torch.Tensor | None = None,
        output_router_logits: bool = False,
    ) -> MoeCausalLMOutput:
        """Produce next-token logits and optional official CE/MoE auxiliary loss.

        Parameters:
            input_ids: Input token ids.
            attention_mask: Optional current token padding mask.
            past_key_values: Optional local cache for autoregressive decoding.
            use_cache: Whether to create or update cache.
            labels: Optional next-token supervision ids.
            output_router_logits: Return per-sparse-layer router logits.
        """
        outputs = self.model(
            input_ids = input_ids,
            attention_mask = attention_mask,
            past_key_values = past_key_values,
            use_cache = use_cache,
            output_router_logits = output_router_logits,
        )
        logits = self.lm_head(outputs.last_hidden_state)
        cross_entropy_loss = None
        aux_loss = None
        loss = None
        if labels is not None:
            cross_entropy_loss = F.cross_entropy(logits[:, :-1].reshape(-1, logits.shape[-1]), labels[:, 1:].reshape(-1))
            if output_router_logits:
                aux_loss = load_balancing_loss(
                    outputs.router_logits,
                    self.config.num_local_experts,
                    self.config.num_experts_per_tok,
                    attention_mask,
                )
                loss = cross_entropy_loss + self.config.router_aux_loss_coef * aux_loss
            else:
                loss = cross_entropy_loss
        return MoeCausalLMOutput(
            logits = logits,
            loss = loss,
            aux_loss = aux_loss,
            past_key_values = outputs.past_key_values,
            router_logits = outputs.router_logits,
        )


class Glm5NextModel(nn.Module):
    """Official GLM5 multimodal feature injection around the local text backbone.

    Parameters:
        config: Combined GLM5 text and vision configuration.
    """

    def __init__(self, config: Glm5NextConfig) -> None:
        """Create visual tower and language model from nested source configs.

        Parameters:
            config: Combined GLM5 configuration.
        """
        super().__init__()
        self.config = config
        self.visual = Glm5NextVisionModel(config.vision_config)
        self.language_model = Glm5NextTextModel(config.text_config)

    def get_image_features(
        self,
        pixel_values: torch.Tensor,
        image_grid_thw: torch.Tensor,
    ) -> tuple[torch.Tensor, ...]:
        """Extract per-image merged visual embeddings.

        Parameters:
            pixel_values: Flattened image patches.
            image_grid_thw: Temporal-height-width image grids.
        """
        vision_outputs = self.visual(pixel_values, image_grid_thw)
        split_sizes = (image_grid_thw.prod(-1) // self.visual.spatial_merge_size**2).tolist()
        return torch.split(vision_outputs.pooler_output, split_sizes)

    def get_video_features(
        self,
        pixel_values_videos: torch.Tensor,
        video_grid_thw: torch.Tensor,
    ) -> tuple[torch.Tensor, ...]:
        """Extract source video features using each frame as a visual packed segment.

        Parameters:
            pixel_values_videos: Flattened video patches.
            video_grid_thw: Original video temporal-height-width grids.
        """
        temporal = video_grid_thw[:, 0]
        spatial = video_grid_thw[:, 1:]
        flattened_spatial = torch.repeat_interleave(spatial, temporal, dim = 0)
        flattened_grid = torch.cat([video_grid_thw.new_ones(flattened_spatial.shape[0], 1), flattened_spatial], dim = 1)
        vision_outputs = self.visual(pixel_values_videos, flattened_grid)
        split_sizes = (video_grid_thw.prod(-1) // self.visual.spatial_merge_size**2).tolist()
        return torch.split(vision_outputs.pooler_output, split_sizes)

    def get_placeholder_mask(
        self,
        input_ids: torch.Tensor,
        inputs_embeds: torch.Tensor,
        image_features: torch.Tensor | None = None,
        video_features: torch.Tensor | None = None,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Build official shared-image-token masks and validate feature counts.

        Parameters:
            input_ids: Input token ids.
            inputs_embeds: Input embeddings used for feature replacement.
            image_features: Optional flattened image features.
            video_features: Optional flattened video features.
        """
        shared_visual_mask = input_ids == self.config.image_token_id
        # GLM5 uses the same special token for images and video; start/end spans disambiguate it.
        in_video_span = (input_ids == self.config.video_start_token_id).cumsum(-1) > (
            input_ids == self.config.video_end_token_id
        ).cumsum(-1)
        image_mask = (shared_visual_mask & ~in_video_span).unsqueeze(-1)
        video_mask = (shared_visual_mask & in_video_span).unsqueeze(-1)
        if image_features is not None and image_mask.sum() * inputs_embeds.shape[-1] != image_features.numel():
            raise ValueError("Image features and image tokens do not match.")
        if video_features is not None and video_mask.sum() * inputs_embeds.shape[-1] != video_features.numel():
            raise ValueError("Video features and video tokens do not match.")
        return image_mask, video_mask

    def forward(
        self,
        input_ids: torch.Tensor | None = None,
        attention_mask: torch.Tensor | None = None,
        past_key_values: Glm5NextCache | None = None,
        inputs_embeds: torch.Tensor | None = None,
        use_cache: bool = False,
        pixel_values: torch.Tensor | None = None,
        pixel_values_videos: torch.Tensor | None = None,
        image_grid_thw: torch.Tensor | None = None,
        video_grid_thw: torch.Tensor | None = None,
        output_router_logits: bool = False,
    ) -> Glm5NextTextModelOutput:
        """Insert visual features into source placeholders then run the text backbone.

        Parameters:
            input_ids: Token ids containing source visual placeholders.
            attention_mask: Optional text padding mask.
            past_key_values: Optional local decoding cache.
            inputs_embeds: Optional precomputed token embeddings.
            use_cache: Whether to return/update cache.
            pixel_values: Optional flattened image patches.
            pixel_values_videos: Optional flattened video patches.
            image_grid_thw: Image grids.
            video_grid_thw: Video grids.
            output_router_logits: Whether sparse-router diagnostics are returned.
        """
        if (input_ids is None) == (inputs_embeds is None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")
        if inputs_embeds is None:
            inputs_embeds = self.language_model.embed_tokens(input_ids)
        if pixel_values is not None:
            if image_grid_thw is None:
                raise ValueError("image_grid_thw is required when pixel_values is provided.")
            image_features = torch.cat(self.get_image_features(pixel_values, image_grid_thw), dim = 0).to(inputs_embeds)
            image_mask, _ = self.get_placeholder_mask(input_ids, inputs_embeds, image_features = image_features)
            inputs_embeds = inputs_embeds.masked_scatter(image_mask, image_features)
        if pixel_values_videos is not None:
            if video_grid_thw is None:
                raise ValueError("video_grid_thw is required when pixel_values_videos is provided.")
            video_features = torch.cat(self.get_video_features(pixel_values_videos, video_grid_thw), dim = 0).to(inputs_embeds)
            _, video_mask = self.get_placeholder_mask(input_ids, inputs_embeds, video_features = video_features)
            inputs_embeds = inputs_embeds.masked_scatter(video_mask, video_features)
        return self.language_model(
            input_ids = None,
            inputs_embeds = inputs_embeds,
            attention_mask = attention_mask,
            past_key_values = past_key_values,
            use_cache = use_cache,
            output_router_logits = output_router_logits,
        )


class Glm5NextForConditionalGeneration(nn.Module):
    """Standalone GLM5 conditional model retaining the official multimodal inputs.

    Parameters:
        config: Combined GLM5 text/vision configuration.
    """

    def __init__(self, config: Glm5NextConfig) -> None:
        """Create source multimodal model and untied LM head.

        Parameters:
            config: Combined GLM5 configuration.
        """
        super().__init__()
        self.config = config
        self.model = Glm5NextModel(config)
        self.lm_head = nn.Linear(config.text_config.hidden_size, config.text_config.vocab_size, bias = False)
        initialize_glm5_next_weights(self.lm_head, config.text_config.initializer_range)

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        past_key_values: Glm5NextCache | None = None,
        labels: torch.Tensor | None = None,
        use_cache: bool = False,
        pixel_values: torch.Tensor | None = None,
        pixel_values_videos: torch.Tensor | None = None,
        image_grid_thw: torch.Tensor | None = None,
        video_grid_thw: torch.Tensor | None = None,
        output_router_logits: bool = False,
        mm_token_type_ids: torch.Tensor | None = None,
    ) -> MoeCausalLMOutput:
        """Run conditional GLM5 logits and optional CE/MoE auxiliary loss.

        Parameters:
            input_ids: Input token ids.
            attention_mask: Optional text padding mask.
            past_key_values: Optional decoding cache.
            labels: Optional causal supervision ids.
            use_cache: Whether to return/update cache.
            pixel_values: Optional image patches.
            pixel_values_videos: Optional video patches.
            image_grid_thw: Image grids.
            video_grid_thw: Video grids.
            output_router_logits: Whether sparse-router diagnostics are returned.
            mm_token_type_ids: Retained official processor/model input; token spans determine routing locally.
        """
        del mm_token_type_ids
        outputs = self.model(
            input_ids = input_ids,
            attention_mask = attention_mask,
            past_key_values = past_key_values,
            use_cache = use_cache,
            pixel_values = pixel_values,
            pixel_values_videos = pixel_values_videos,
            image_grid_thw = image_grid_thw,
            video_grid_thw = video_grid_thw,
            output_router_logits = output_router_logits,
        )
        logits = self.lm_head(outputs.last_hidden_state)
        cross_entropy_loss = None
        aux_loss = None
        loss = None
        if labels is not None:
            cross_entropy_loss = F.cross_entropy(logits[:, :-1].reshape(-1, logits.shape[-1]), labels[:, 1:].reshape(-1))
            if output_router_logits:
                aux_loss = load_balancing_loss(
                    outputs.router_logits,
                    self.config.text_config.num_local_experts,
                    self.config.text_config.num_experts_per_tok,
                    attention_mask,
                )
                loss = cross_entropy_loss + self.config.text_config.router_aux_loss_coef * aux_loss
            else:
                loss = cross_entropy_loss
        return MoeCausalLMOutput(
            logits = logits,
            loss = loss,
            aux_loss = aux_loss,
            past_key_values = outputs.past_key_values,
            router_logits = outputs.router_logits,
        )


__all__ = [
    "Glm5NextCache",
    "Glm5NextForConditionalGeneration",
    "Glm5NextForCausalLM",
    "Glm5NextModel",
    "Glm5NextTextAttention",
    "Glm5NextTextDecoderLayer",
    "Glm5NextTextIndexer",
    "Glm5NextTextLinearAttention",
    "Glm5NextTextModel",
    "Glm5NextTextMoE",
    "recurrent_kimi_delta_attention",
]
