#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/glm5_next/modular_glm5_next.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_glm5_next.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 the HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""GLM5-Next processor helpers without the Transformers processor runtime."""

from __future__ import annotations

import os
import sys
from typing import Any

import numpy as np

sys.path.append(os.getcwd())

try:
    from ..utils.processing import MultiModalData, ProcessorMixin
except ImportError:
    sys.path.append(os.path.dirname(os.path.dirname(__file__)))
    from utils.processing import MultiModalData, ProcessorMixin


class Glm5NextProcessor(ProcessorMixin):
    """Official GLM5 placeholder expansion and multimodal token type handling.

    Parameters:
        image_processor: Image processor exposing merge geometry.
        tokenizer: GLM tokenizer exposing special-token conversion and decode.
        video_processor: Video processor exposing merge geometry and metadata.
        chat_template: Optional retained prompt template.
    """

    def __init__(
        self,
        image_processor: Any = None,
        tokenizer: Any = None,
        video_processor: Any = None,
        chat_template: str | None = None,
        **kwargs: Any,
    ) -> None:
        """Initialize source image/video token ids.

        Parameters:
            image_processor: Image preprocessor.
            tokenizer: GLM tokenizer.
            video_processor: Video preprocessor.
            chat_template: Optional prompt template.
            **kwargs: Reserved source-compatible arguments.
        """
        del kwargs
        if tokenizer is None:
            raise ValueError("Glm5NextProcessor requires a tokenizer.")
        self.image_token = "<|image|>" if not hasattr(tokenizer, "image_token") else tokenizer.image_token
        self.video_token = "<|video|>" if not hasattr(tokenizer, "video_token") else tokenizer.video_token
        self.image_token_id = tokenizer.image_token_id if getattr(tokenizer, "image_token_id", None) else tokenizer.convert_tokens_to_ids(self.image_token)
        self.video_token_id = tokenizer.video_token_id if getattr(tokenizer, "video_token_id", None) else tokenizer.convert_tokens_to_ids(self.video_token)
        super().__init__(image_processor, tokenizer, video_processor, chat_template = chat_template)
        self.video_start_id = tokenizer.convert_tokens_to_ids("<|begin_of_video|>")
        self.video_end_id = tokenizer.convert_tokens_to_ids("<|end_of_video|>")

    def replace_image_token(self, image_inputs: dict[str, Any], image_idx: int, **kwargs: Any) -> str:
        """Expand one source image placeholder.

        Parameters:
            image_inputs: Image processor output containing ``image_grid_thw``.
            image_idx: Image index in the processor batch.
            **kwargs: Retained upstream callback arguments.
        """
        del kwargs
        merge_length = self.image_processor.merge_size**2
        num_image_tokens = image_inputs["image_grid_thw"][image_idx].prod() // merge_length
        return self.image_token * int(num_image_tokens)

    def replace_video_token(self, video_inputs: dict[str, Any], video_idx: int, **kwargs: Any) -> str:
        """Build the official timestamped video-frame placeholder structure.

        Parameters:
            video_inputs: Video processor output containing grids and metadata.
            video_idx: Video index in the processor batch.
            **kwargs: Retained upstream callback arguments.
        """
        del kwargs
        merge_length = self.video_processor.merge_size**2
        num_frames = int(video_inputs["video_grid_thw"][video_idx][0])
        num_image_tokens = int(video_inputs["video_grid_thw"][video_idx].prod() // merge_length // num_frames)
        metadata = video_inputs["video_metadata"][video_idx]
        if metadata.fps is None:
            # GLM5_NEXT requires timestamps; the official fallback is 24 fps.
            metadata.fps = 24
        timestamps = metadata.timestamps[::2]  # mrope
        selected_timestamps = list(timestamps[:num_frames])
        while len(selected_timestamps) < num_frames:
            selected_timestamps.append(selected_timestamps[-1] if selected_timestamps else 0)
        return "".join(self.replace_frame_token_id(timestamp, num_image_tokens) for timestamp in selected_timestamps)

    def _get_num_multimodal_tokens(
        self,
        image_sizes: list[list[int]] | None = None,
        video_sizes: list[list[int]] | None = None,
        **kwargs: Any,
    ) -> MultiModalData:
        """Calculate official merged placeholder counts.

        Parameters:
            image_sizes: Image ``(height, width)`` values.
            video_sizes: Video ``(frames, height, width)`` values.
            **kwargs: Image/video processor overrides.
        """
        vision_data: dict[str, list[int]] = {}
        if image_sizes is not None:
            image_kwargs = dict(kwargs)
            merge_size = image_kwargs.get("merge_size") or self.image_processor.merge_size
            patches = [self.image_processor.get_number_of_image_patches(*size, image_kwargs) for size in image_sizes]
            vision_data.update({"num_image_tokens": [count // merge_size**2 for count in patches], "num_image_patches": patches})
        if video_sizes is not None:
            video_kwargs = dict(kwargs)
            merge_size = video_kwargs.get("merge_size") or self.video_processor.merge_size
            patches = [self.video_processor.get_number_of_video_patches(*size, video_kwargs) for size in video_sizes]
            vision_data["num_video_tokens"] = [count // merge_size**2 for count in patches]
        return MultiModalData(**vision_data)

    def post_process_image_text_to_text(
        self,
        generated_outputs: Any,
        skip_special_tokens: bool = True,
        clean_up_tokenization_spaces: bool = False,
        **kwargs: Any,
    ) -> list[str]:
        """Decode generated token ids with the supplied tokenizer.

        Parameters:
            generated_outputs: Generated token ids.
            skip_special_tokens: Whether special tokens are omitted.
            clean_up_tokenization_spaces: Whether tokenizer whitespace cleanup is used.
            **kwargs: Extra tokenizer decode options.
        """
        return self.tokenizer.batch_decode(
            generated_outputs,
            skip_special_tokens = skip_special_tokens,
            clean_up_tokenization_spaces = clean_up_tokenization_spaces,
            **kwargs,
        )

    @property
    def model_input_names(self) -> list[str]:
        """Return component inputs plus source multimodal token type ids.

        Parameters:
            None.
        """
        return super().model_input_names + ["mm_token_type_ids"]

    def create_mm_token_type_ids(self, input_ids: list[list[int]]) -> list[list[int]]:
        """Mark image and video placeholders using GLM5's shared visual token.

        Parameters:
            input_ids: Potentially unpadded token-id sequences.
        """
        # Iterate separately: unpadded lists cannot be converted to one NumPy matrix.
        token_types = []
        for ids in input_ids:
            array_ids = np.array(ids)
            types = np.zeros_like(array_ids)
            starts = np.cumsum(array_ids == self.video_start_id, axis = 0)
            ends = np.cumsum(array_ids == self.video_end_id, axis = 0)
            is_video = starts > ends
            types[(array_ids == self.image_token_id) & is_video] = 2
            types[(array_ids == self.image_token_id) & ~is_video] = 1
            token_types.append(types.tolist())
        return token_types

    def replace_frame_token_id(self, timestamp_sec: float, num_image_tokens: int = 1) -> str:
        """Construct an official single timestamped image-frame placeholder.

        Parameters:
            timestamp_sec: Frame timestamp in seconds.
            num_image_tokens: Number of merged image tokens in the frame.
        """
        return f"<|begin_of_image|>{self.image_token * num_image_tokens}<|end_of_image|>{timestamp_sec:.1f} seconds"


__all__ = ["Glm5NextProcessor"]
