#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/gpt_oss/modular_gpt_oss.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_gpt_oss.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2025 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""A small, self-contained PyTorch implementation of GPT-OSS.

Key architecture comments retain the intent of the Hugging Face implementation.
"""

import math
import sys
from pathlib import Path

import torch
from torch import nn
from torch.nn import functional as F

try:
    from .configuration_gpt_oss import GptOssConfig
    from .utils import (
        GptOssCausalLMOutput,
        GptOssModelOutput,
        KVCache,
        YaRNRotaryEmbedding,
        apply_rotary_pos_emb,
        build_attention_mask,
        load_balancing_loss,
        repeat_kv,
    )
except ImportError:
    sys.path.append(str(Path(__file__).resolve().parent.parent))
    from configuration_gpt_oss import GptOssConfig
    from utils import (
        GptOssCausalLMOutput,
        GptOssModelOutput,
        KVCache,
        YaRNRotaryEmbedding,
        apply_rotary_pos_emb,
        build_attention_mask,
        load_balancing_loss,
        repeat_kv,
    )


class GptOssRMSNorm(nn.Module):
    """Root-mean-square normalization used before attention and MoE blocks."""

    def __init__(self, hidden_size: int, eps: float = 1e-6) -> None:
        """Initialize a learnable RMS scale.

        Parameters:
            hidden_size: Size of the hidden-state final dimension.
            eps: Numerical stabilizer added to the RMS variance.
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        """Normalize hidden states in float32, then restore their input dtype.

        Parameters:
            hidden_states: Tensor whose final dimension is ``hidden_size``.
        """
        input_dtype = hidden_states.dtype
        # 原版说明 / Upstream note: this is the main difference from Llama RMSNorm.
        normalized_states = hidden_states.float()
        variance = normalized_states.pow(2).mean(dim = -1, keepdim = True)
        normalized_states = normalized_states * torch.rsqrt(variance + self.variance_epsilon)
        return (self.weight * normalized_states).to(dtype = input_dtype)


class GptOssTopKRouter(nn.Module):
    """Select a sparse set of experts and normalize their routing weights."""

    def __init__(self, config: GptOssConfig) -> None:
        """Initialize the linear router from a GPT-OSS configuration.

        Parameters:
            config: Model configuration containing expert and hidden dimensions.
        """
        super().__init__()
        self.top_k = config.num_experts_per_tok
        self.num_experts = config.num_local_experts
        self.weight = nn.Parameter(torch.empty(self.num_experts, config.hidden_size))
        self.bias = nn.Parameter(torch.empty(self.num_experts))

    def forward(self, hidden_states: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        """Compute logits, selected expert weights, and selected expert indices.

        Parameters:
            hidden_states: Flattened token states shaped ``[tokens, hidden_size]``.
        """
        router_logits = F.linear(hidden_states, self.weight, self.bias)
        # 每个 token 只保留 top-k 专家 / Keep only top-k experts for each token.
        top_values, router_indices = torch.topk(router_logits, self.top_k, dim = -1)
        router_scores = F.softmax(top_values, dim = -1, dtype = torch.float32).to(dtype = hidden_states.dtype)
        return router_logits, router_scores, router_indices


class GptOssExperts(nn.Module):
    """Sparse GPT-OSS expert parameters and selected-expert execution."""

    def __init__(self, config: GptOssConfig) -> None:
        """Allocate per-expert gate/up and down projections.

        Parameters:
            config: Model configuration defining expert dimensions and count.
        """
        super().__init__()
        self.intermediate_size = config.intermediate_size
        self.num_experts = config.num_local_experts
        self.hidden_size = config.hidden_size
        self.gate_up_proj = nn.Parameter(
            torch.empty(self.num_experts, self.hidden_size, 2 * self.intermediate_size)
        )
        self.gate_up_proj_bias = nn.Parameter(torch.empty(self.num_experts, 2 * self.intermediate_size))
        self.down_proj = nn.Parameter(torch.empty(self.num_experts, self.intermediate_size, self.hidden_size))
        self.down_proj_bias = nn.Parameter(torch.empty(self.num_experts, self.hidden_size))
        self.alpha = 1.702
        self.limit = 7.0

    def _apply_gate(self, gate_up: torch.Tensor) -> torch.Tensor:
        """Apply GPT-OSS's clipped gate/up activation.

        Parameters:
            gate_up: Interleaved gate and up activations shaped ``[..., 2 * intermediate_size]``.
        """
        gate, up = gate_up[..., ::2], gate_up[..., 1::2]
        gate = gate.clamp(max = self.limit)
        up = up.clamp(min = -self.limit, max = self.limit)
        glu = gate * torch.sigmoid(gate * self.alpha)
        return (up + 1.0) * glu

    def forward(
        self,
        hidden_states: torch.Tensor,
        router_indices: torch.Tensor,
        routing_weights: torch.Tensor,
    ) -> torch.Tensor:
        """Route every token through its selected experts and sum weighted outputs.

        Parameters:
            hidden_states: Flattened token states shaped ``[tokens, hidden_size]``.
            router_indices: Selected expert IDs shaped ``[tokens, top_k]``.
            routing_weights: Normalized selected weights shaped ``[tokens, top_k]``.
        """
        next_states = torch.zeros_like(hidden_states)
        for expert_idx in range(self.num_experts):
            token_indices, top_k_positions = torch.where(router_indices == expert_idx)
            if token_indices.numel() == 0:
                continue

            # 原版语义 / Upstream behavior: process only tokens that selected this expert.
            current_states = hidden_states[token_indices]
            gate_up = current_states @ self.gate_up_proj[expert_idx] + self.gate_up_proj_bias[expert_idx]
            gated_output = self._apply_gate(gate_up)
            expert_output = gated_output @ self.down_proj[expert_idx] + self.down_proj_bias[expert_idx]
            weighted_output = expert_output * routing_weights[token_indices, top_k_positions].unsqueeze(-1)
            next_states.index_add_(0, token_indices, weighted_output.to(dtype = hidden_states.dtype))
        return next_states


class GptOssMLP(nn.Module):
    """Top-k mixture-of-experts feed-forward block."""

    def __init__(self, config: GptOssConfig) -> None:
        """Create router and expert modules.

        Parameters:
            config: Model configuration used by the MoE block.
        """
        super().__init__()
        self.router = GptOssTopKRouter(config)
        self.experts = GptOssExperts(config)

    def forward(self, hidden_states: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        """Run sparse routing and restore the original batch/sequence shape.

        Parameters:
            hidden_states: Tensor shaped ``[batch, tokens, hidden_size]``.
        """
        batch_size, sequence_length, hidden_size = hidden_states.shape
        flat_states = hidden_states.reshape(-1, hidden_size)
        router_logits, router_scores, router_indices = self.router(flat_states)
        output_states = self.experts(flat_states, router_indices, router_scores)
        return output_states.reshape(batch_size, sequence_length, hidden_size), router_logits


class GptOssAttention(nn.Module):
    """Grouped-query causal attention with YaRN RoPE and attention sinks."""

    def __init__(self, config: GptOssConfig, layer_idx: int) -> None:
        """Create the projections and sink parameters for one attention layer.

        Parameters:
            config: Model configuration used to size attention projections.
            layer_idx: Layer index used to address a KV cache.
        """
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = config.head_dim
        self.num_attention_heads = config.num_attention_heads
        self.num_key_value_heads = config.num_key_value_heads
        self.num_key_value_groups = self.num_attention_heads // self.num_key_value_heads
        self.scaling = 1.0 / math.sqrt(self.head_dim)
        self.q_proj = nn.Linear(
            config.hidden_size,
            self.num_attention_heads * self.head_dim,
            bias = config.attention_bias,
        )
        self.k_proj = nn.Linear(
            config.hidden_size,
            self.num_key_value_heads * self.head_dim,
            bias = config.attention_bias,
        )
        self.v_proj = nn.Linear(
            config.hidden_size,
            self.num_key_value_heads * self.head_dim,
            bias = config.attention_bias,
        )
        self.o_proj = nn.Linear(
            self.num_attention_heads * self.head_dim,
            config.hidden_size,
            bias = config.attention_bias,
        )
        self.sinks = nn.Parameter(torch.empty(self.num_attention_heads))

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: torch.Tensor | None,
        past_key_values: KVCache | None,
        use_cache: bool,
        layer_type: str,
    ) -> torch.Tensor:
        """Compute attention output for one decoder layer.

        Parameters:
            hidden_states: Input states shaped ``[batch, tokens, hidden_size]``.
            position_embeddings: YaRN cosine and sine tensors for current tokens.
            attention_mask: Optional 1/0 mask over cached and current key tokens.
            past_key_values: Optional per-layer KV cache.
            use_cache: Whether new K/V tensors should be stored in the cache.
            layer_type: Full or sliding attention mode for this decoder layer.
        """
        batch_size, query_length, _ = hidden_states.shape
        projection_shape = (batch_size, query_length, -1, self.head_dim)
        query_states = self.q_proj(hidden_states).view(projection_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(projection_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(projection_shape).transpose(1, 2)
        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        past_length = 0
        if past_key_values is not None:
            past_length = past_key_values.get_seq_length(self.layer_idx)
            if use_cache:
                key_states, value_states = past_key_values.update(key_states, value_states, self.layer_idx)

        key_states = repeat_kv(key_states, self.num_key_value_groups)
        value_states = repeat_kv(value_states, self.num_key_value_groups)
        additive_mask = build_attention_mask(
            attention_mask = attention_mask,
            query_length = query_length,
            key_length = key_states.shape[-2],
            past_length = past_length,
            layer_type = layer_type,
            sliding_window = self.config.sliding_window,
            device = hidden_states.device,
            dtype = query_states.dtype,
        )

        attention_logits = torch.matmul(query_states, key_states.transpose(-2, -1)) * self.scaling
        attention_logits = attention_logits + additive_mask
        # 与 Llama 的关键差异 / Main difference from Llama: append one sink logit per attention head.
        sink_logits = self.sinks.reshape(1, -1, 1, 1).expand(batch_size, -1, query_length, -1)
        combined_logits = torch.cat([attention_logits, sink_logits], dim = -1)
        # 原版说明 / Upstream note: clamp logits indirectly to avoid BF16/FP16 overflow in training.
        combined_logits = combined_logits - combined_logits.max(dim = -1, keepdim = True).values
        # Sink 只参与概率归一化，不参与 value 聚合 / Drop the sink before value aggregation.
        attention_weights = F.softmax(combined_logits, dim = -1, dtype = torch.float32)[..., :-1]
        attention_weights = F.dropout(
            attention_weights,
            p = self.config.attention_dropout if self.training else 0.0,
            training = self.training,
        ).to(dtype = value_states.dtype)
        attention_output = torch.matmul(attention_weights, value_states)
        attention_output = attention_output.transpose(1, 2).reshape(batch_size, query_length, -1).contiguous()
        return self.o_proj(attention_output)


class GptOssDecoderLayer(nn.Module):
    """One pre-norm GPT-OSS attention and MoE decoder block."""

    def __init__(self, config: GptOssConfig, layer_idx: int) -> None:
        """Create attention, MoE, and RMS normalization modules.

        Parameters:
            config: Model configuration used by this decoder layer.
            layer_idx: Layer index used by attention cache lookup.
        """
        super().__init__()
        self.self_attn = GptOssAttention(config, layer_idx)
        self.mlp = GptOssMLP(config)
        self.input_layernorm = GptOssRMSNorm(config.hidden_size, eps = config.rms_norm_eps)
        self.post_attention_layernorm = GptOssRMSNorm(config.hidden_size, eps = config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: torch.Tensor | None,
        past_key_values: KVCache | None,
        use_cache: bool,
        layer_type: str,
    ) -> tuple[torch.Tensor, torch.Tensor]:
        """Apply pre-norm attention and sparse MoE residual sublayers.

        Parameters:
            hidden_states: Input tensor shaped ``[batch, tokens, hidden_size]``.
            position_embeddings: YaRN cosine and sine tensors for current tokens.
            attention_mask: Optional valid-token mask for attention keys.
            past_key_values: Optional cache holding past attention K/V tensors.
            use_cache: Whether to append the current K/V tensors to the cache.
            layer_type: Full or sliding attention mode for this layer.
        """
        residual = hidden_states
        normalized_states = self.input_layernorm(hidden_states)
        # Self Attention / 自注意力。
        attention_output = self.self_attn(
            normalized_states,
            position_embeddings = position_embeddings,
            attention_mask = attention_mask,
            past_key_values = past_key_values,
            use_cache = use_cache,
            layer_type = layer_type,
        )
        hidden_states = residual + attention_output

        residual = hidden_states
        normalized_states = self.post_attention_layernorm(hidden_states)
        # Fully Connected / 前馈 MoE；与 Llama 不同，这里使用 router scores。
        mlp_output, router_logits = self.mlp(normalized_states)
        return residual + mlp_output, router_logits


class GptOssModel(nn.Module):
    """GPT-OSS decoder stack without a language-model head."""

    def __init__(self, config: GptOssConfig) -> None:
        """Create embeddings, decoder layers, YaRN module, and final normalization.

        Parameters:
            config: Model configuration defining the decoder stack.
        """
        super().__init__()
        self.config = config
        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, config.pad_token_id)
        self.layers = nn.ModuleList(
            [GptOssDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = GptOssRMSNorm(config.hidden_size, eps = config.rms_norm_eps)
        self.rotary_emb = YaRNRotaryEmbedding(config)
        self.apply(self._init_weights)

    def _init_weights(self, module: nn.Module) -> None:
        """Initialize modules following the GPT-OSS normal-initialization convention.

        Parameters:
            module: Child module visited by ``nn.Module.apply``.
        """
        std = self.config.initializer_range
        if isinstance(module, nn.Linear):
            nn.init.normal_(module.weight, mean = 0.0, std = std)
            if module.bias is not None:
                nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            nn.init.normal_(module.weight, mean = 0.0, std = std)
            if module.padding_idx is not None:
                module.weight.data[module.padding_idx].zero_()
        elif isinstance(module, GptOssExperts):
            nn.init.normal_(module.gate_up_proj, mean = 0.0, std = std)
            nn.init.zeros_(module.gate_up_proj_bias)
            nn.init.normal_(module.down_proj, mean = 0.0, std = std)
            nn.init.zeros_(module.down_proj_bias)
        elif isinstance(module, GptOssAttention):
            nn.init.normal_(module.sinks, mean = 0.0, std = std)
        elif isinstance(module, GptOssTopKRouter):
            nn.init.normal_(module.weight, mean = 0.0, std = std)
            nn.init.normal_(module.bias, mean = 0.0, std = std)

    def forward(
        self,
        input_ids: torch.Tensor | None = None,
        attention_mask: torch.Tensor | None = None,
        position_ids: torch.Tensor | None = None,
        past_key_values: KVCache | None = None,
        inputs_embeds: torch.Tensor | None = None,
        use_cache: bool | None = None,
        output_router_logits: bool = False,
    ) -> GptOssModelOutput:
        """Embed tokens and run the GPT-OSS decoder stack.

        Parameters:
            input_ids: Token IDs shaped ``[batch, tokens]``.
            attention_mask: Optional 1/0 mask over cached and current tokens.
            position_ids: Optional absolute positions shaped ``[batch, tokens]``.
            past_key_values: Optional cache from a previous decoding call.
            inputs_embeds: Optional precomputed embeddings instead of ``input_ids``.
            use_cache: Whether to create or append to a KV cache.
            output_router_logits: Whether to retain each layer's router logits.
        """
        if (input_ids is None) == (inputs_embeds is None):
            raise ValueError("Specify exactly one of input_ids or inputs_embeds")
        use_cache = self.config.use_cache if use_cache is None else use_cache
        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)
        if use_cache and past_key_values is None:
            past_key_values = KVCache()

        past_length = past_key_values.get_seq_length() if past_key_values is not None else 0
        if position_ids is None:
            position_ids = torch.arange(
                past_length,
                past_length + inputs_embeds.shape[1],
                device = inputs_embeds.device,
            ).unsqueeze(0)
        if position_ids.shape[0] == 1 and inputs_embeds.shape[0] > 1:
            position_ids = position_ids.expand(inputs_embeds.shape[0], -1)

        position_embeddings = self.rotary_emb(inputs_embeds, position_ids)
        hidden_states = inputs_embeds
        all_router_logits = []
        for layer_idx, decoder_layer in enumerate(self.layers):
            hidden_states, router_logits = decoder_layer(
                hidden_states,
                position_embeddings = position_embeddings,
                attention_mask = attention_mask,
                past_key_values = past_key_values,
                use_cache = use_cache,
                layer_type = self.config.layer_types[layer_idx],
            )
            if output_router_logits:
                all_router_logits.append(router_logits)

        return GptOssModelOutput(
            last_hidden_state = self.norm(hidden_states),
            past_key_values = past_key_values if use_cache else None,
            router_logits = tuple(all_router_logits) if output_router_logits else None,
        )


class GptOssForCausalLM(nn.Module):
    """GPT-OSS decoder with a causal language-model projection head."""

    def __init__(self, config: GptOssConfig) -> None:
        """Create the decoder model and vocabulary projection head.

        Parameters:
            config: Model configuration used by the decoder and output projection.
        """
        super().__init__()
        self.config = config
        self.model = GptOssModel(config)
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias = False)
        self.model._init_weights(self.lm_head)
        if config.tie_word_embeddings:
            self.lm_head.weight = self.model.embed_tokens.weight

    def forward(
        self,
        input_ids: torch.Tensor,
        attention_mask: torch.Tensor | None = None,
        past_key_values: KVCache | None = None,
        use_cache: bool | None = None,
        labels: torch.Tensor | None = None,
        output_router_logits: bool | None = None,
    ) -> GptOssCausalLMOutput:
        """Produce causal logits and optional supervised MoE training losses.

        Parameters:
            input_ids: Token IDs shaped ``[batch, tokens]``.
            attention_mask: Optional 1/0 valid-token mask.
            past_key_values: Optional cache returned by an earlier forward call.
            use_cache: Whether to return and update a per-layer KV cache.
            labels: Optional target IDs; ``-100`` entries are ignored by cross entropy.
            output_router_logits: Whether router logits are returned for inspection.
        """
        output_router_logits = self.config.output_router_logits if output_router_logits is None else output_router_logits
        needs_router_logits = output_router_logits or labels is not None
        model_outputs = self.model(
            input_ids = input_ids,
            attention_mask = attention_mask,
            past_key_values = past_key_values,
            use_cache = use_cache,
            output_router_logits = needs_router_logits,
        )
        logits = self.lm_head(model_outputs.last_hidden_state)
        cross_entropy_loss = None
        aux_loss = None
        loss = None
        if labels is not None:
            if labels.shape != input_ids.shape:
                raise ValueError("labels must have the same shape as input_ids")
            if input_ids.shape[1] < 2:
                cross_entropy_loss = logits.sum() * 0.0
            else:
                cross_entropy_loss = F.cross_entropy(
                    logits[:, :-1, :].reshape(-1, self.config.vocab_size),
                    labels[:, 1:].reshape(-1),
                    ignore_index = -100,
                )
            aux_loss = load_balancing_loss(
                model_outputs.router_logits,
                num_experts = self.config.num_local_experts,
                top_k = self.config.num_experts_per_tok,
                attention_mask = attention_mask,
            )
            loss = cross_entropy_loss + self.config.router_aux_loss_coef * aux_loss

        return GptOssCausalLMOutput(
            logits = logits,
            loss = loss,
            cross_entropy_loss = cross_entropy_loss,
            aux_loss = aux_loss,
            past_key_values = model_outputs.past_key_values,
            router_logits = model_outputs.router_logits if output_router_logits else None,
        )
